fadvise: add missing include ctype.h
Fix warning:
fadvise.c:21:18: error: implicit declaration of function ‘toupper’ [-Werror=implicit-function-declaration]
   21 |         str[i] = toupper( str[i] );