fincore: remove unused variable errstr
Fix warning:
fincore.c:37:11: error: unused variable ‘errstr’ [-Werror=unused-variable]
   37 |     char *errstr;